In [2]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init

# Load data
X = torch.tensor([[2.4]], dtype=torch.float32)
y = torch.tensor([0], dtype=torch.int64)

In [3]:
print(X)
print(y)

tensor([[2.4000]])
tensor([0])


In [4]:
# Define the model
class SoftmaxRegression(nn.Module):
    def __init__(self):
        super(SoftmaxRegression, self).__init__()
        self.linear1 = nn.Linear(1, 1)
        self.linear2 = nn.Linear(1, 1)
        self.linear3 = nn.Linear(1, 1)
        self.linear4 = nn.Linear(1, 1)
        self.linear5 = nn.Linear(1, 1)
        self.linear6 = nn.Linear(1, 1)
        self.linear7 = nn.Linear(1, 1)
        self.linear8 = nn.Linear(1, 2)
        self.sigmoid = nn.Sigmoid()

        # Initialize weights
        init.normal_(self.linear1.weight, mean=0, std=1)
        init.normal_(self.linear2.weight, mean=0, std=1)
        init.normal_(self.linear3.weight, mean=0, std=1)
        init.normal_(self.linear4.weight, mean=0, std=1)
        init.normal_(self.linear5.weight, mean=0, std=1)
        init.normal_(self.linear6.weight, mean=0, std=1)
        init.normal_(self.linear7.weight, mean=0, std=1)
        init.normal_(self.linear8.weight, mean=0, std=1)

        # If you also want to initialize the biases to zero (this is optional)
        init.zeros_(self.linear1.bias)
        init.zeros_(self.linear2.bias)
        init.zeros_(self.linear3.bias)
        init.zeros_(self.linear4.bias)
        init.zeros_(self.linear5.bias)
        init.zeros_(self.linear6.bias)
        init.zeros_(self.linear7.bias)
        init.zeros_(self.linear8.bias)
        
        # set value (for illustration)
        #self.linear.weight.data = torch.Tensor([[0.2], [-0.1]])
        #self.linear.bias.data = torch.Tensor([0.1, 0.05])
        
    def forward(self, x):
        x = self.linear1(x)
        x = self.sigmoid(x)
        x = self.linear2(x)
        x = self.sigmoid(x)
        x = self.linear3(x)
        x = self.sigmoid(x)
        x = self.linear4(x)
        x = self.sigmoid(x)
        x = self.linear5(x)
        x = self.sigmoid(x)
        x = self.linear6(x)
        x = self.sigmoid(x)
        x = self.linear7(x)
        x = self.sigmoid(x)
        x = self.linear8(x)
        return x

model = SoftmaxRegression()

In [5]:
print(model.linear1.weight)
print(model.linear1.bias)

Parameter containing:
tensor([[-0.3589]], requires_grad=True)
Parameter containing:
tensor([0.], requires_grad=True)


In [6]:
print(model.linear2.weight)
print(model.linear2.bias)

Parameter containing:
tensor([[-1.6835]], requires_grad=True)
Parameter containing:
tensor([0.], requires_grad=True)


In [7]:
print(model.linear3.weight)
print(model.linear3.bias)

Parameter containing:
tensor([[-0.1407]], requires_grad=True)
Parameter containing:
tensor([0.], requires_grad=True)


In [8]:
print(model.linear4.weight)
print(model.linear4.bias)

Parameter containing:
tensor([[1.0128]], requires_grad=True)
Parameter containing:
tensor([0.], requires_grad=True)


In [9]:
print(model.linear5.weight)
print(model.linear5.bias)

Parameter containing:
tensor([[-1.1481]], requires_grad=True)
Parameter containing:
tensor([0.], requires_grad=True)


In [10]:
print(model.linear6.weight)
print(model.linear6.bias)

Parameter containing:
tensor([[0.1349]], requires_grad=True)
Parameter containing:
tensor([0.], requires_grad=True)


In [11]:
print(model.linear7.weight)
print(model.linear7.bias)

Parameter containing:
tensor([[-0.8774]], requires_grad=True)
Parameter containing:
tensor([0.], requires_grad=True)


In [12]:
print(model.linear8.weight)
print(model.linear8.bias)

Parameter containing:
tensor([[-0.4452],
        [ 0.0295]], requires_grad=True)
Parameter containing:
tensor([0., 0.], requires_grad=True)


In [13]:
# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Training loop
max_epoch = 1
for epoch in range(max_epoch):
    xi = X[0].unsqueeze(0)
    yi = y[0].unsqueeze(0)

    print(f'xi: {xi}')
    print(f'yi: {yi}')
    
    # Zero the gradients
    optimizer.zero_grad()
    
    # Forward pass
    outputs = model(xi)
    print(f'outputs: {outputs.data}')
    
    loss = criterion(outputs, yi)
    print(f'loss: {loss}')
    
    # Backward pass and optimization
    loss.backward()
    optimizer.step()
    break

xi: tensor([[2.4000]])
yi: tensor([0])
outputs: tensor([[-0.1735,  0.0115]])
loss: 0.7899288535118103


In [14]:
print(model.linear1.weight.grad)
print(model.linear1.bias.grad)

tensor([[7.6823e-07]])
tensor([3.2010e-07])


In [ ]:
print(model.linear2.weight.grad)
print(model.linear2.bias.grad)

In [ ]:
print(model.linear3.weight.grad)
print(model.linear3.bias.grad)

In [ ]:
print(model.linear4.weight.grad)
print(model.linear4.bias.grad)

In [ ]:
print(model.linear5.weight.grad)
print(model.linear5.bias.grad)

In [ ]:
print(model.linear6.weight.grad)
print(model.linear6.bias.grad)

In [ ]:
print(model.linear7.weight.grad)
print(model.linear7.bias.grad)

In [ ]:
print(model.linear8.weight.grad)
print(model.linear8.bias.grad)

In [ ]:
print(model.linear1.weight)
print(model.linear1.bias)

In [ ]:
print(model.linear2.weight)
print(model.linear2.bias)

In [ ]:
print(model.linear3.weight)
print(model.linear3.bias)

In [ ]:
print(model.linear4.weight)
print(model.linear4.bias)

In [ ]:
print(model.linear5.weight)
print(model.linear5.bias)

In [ ]:
print(model.linear6.weight)
print(model.linear6.bias)

In [ ]:
print(model.linear7.weight)
print(model.linear7.bias)

In [ ]:
print(model.linear8.weight)
print(model.linear8.bias)