In [53]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init

# Load data
X = torch.tensor([[2.4]], dtype=torch.float32)
y = torch.tensor([0], dtype=torch.int64)

In [54]:
print(X)
print(y)

tensor([[2.4000]])
tensor([0])


In [55]:
# Define the model
class SoftmaxRegression(nn.Module):
    def __init__(self):
        super(SoftmaxRegression, self).__init__()
        self.linear1 = nn.Linear(1, 1)
        self.linear2 = nn.Linear(1, 1)
        self.linear3 = nn.Linear(1, 1)
        self.linear4 = nn.Linear(1, 1)
        self.linear5 = nn.Linear(1, 2)
        self.sigmoid = nn.Sigmoid()

        # Initialize weights
        init.normal_(self.linear1.weight, mean=0, std=1)
        init.normal_(self.linear2.weight, mean=0, std=1)
        init.normal_(self.linear3.weight, mean=0, std=1)
        init.normal_(self.linear4.weight, mean=0, std=1)
        init.normal_(self.linear5.weight, mean=0, std=1)

        # If you also want to initialize the biases to zero (this is optional)
        init.zeros_(self.linear1.bias)
        init.zeros_(self.linear2.bias)
        init.zeros_(self.linear3.bias)
        init.zeros_(self.linear4.bias)
        init.zeros_(self.linear5.bias)
        
        # set value (for illustration)
        #self.linear.weight.data = torch.Tensor([[0.2], [-0.1]])
        #self.linear.bias.data = torch.Tensor([0.1, 0.05])
        
    def forward(self, x):
        x = self.linear1(x)
        x = self.sigmoid(x)
        x = self.linear2(x)
        x = self.sigmoid(x)
        x = self.linear3(x)
        x = self.sigmoid(x)
        x = self.linear4(x)
        x = self.sigmoid(x)
        x = self.linear5(x)
        return x

model = SoftmaxRegression()

In [56]:
print(model.linear1.weight)
print(model.linear1.bias)

Parameter containing:
tensor([[0.9197]], requires_grad=True)
Parameter containing:
tensor([0.], requires_grad=True)


In [57]:
print(model.linear2.weight)
print(model.linear2.bias)

Parameter containing:
tensor([[-0.8128]], requires_grad=True)
Parameter containing:
tensor([0.], requires_grad=True)


In [58]:
print(model.linear3.weight)
print(model.linear3.bias)

Parameter containing:
tensor([[1.4712]], requires_grad=True)
Parameter containing:
tensor([0.], requires_grad=True)


In [59]:
print(model.linear4.weight)
print(model.linear4.bias)

Parameter containing:
tensor([[-0.7767]], requires_grad=True)
Parameter containing:
tensor([0.], requires_grad=True)


In [60]:
print(model.linear5.weight)
print(model.linear5.bias)

Parameter containing:
tensor([[-0.3096],
        [ 1.1333]], requires_grad=True)
Parameter containing:
tensor([0., 0.], requires_grad=True)


In [61]:
# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Training loop
max_epoch = 1
for epoch in range(max_epoch):
    xi = X[0].unsqueeze(0)
    yi = y[0].unsqueeze(0)

    print(f'xi: {xi}')
    print(f'yi: {yi}')
    
    # Zero the gradients
    optimizer.zero_grad()
    
    # Forward pass
    outputs = model(xi)
    print(f'outputs: {outputs.data}')
    
    loss = criterion(outputs, yi)
    print(f'loss: {loss}')
    
    # Backward pass and optimization
    loss.backward()
    optimizer.step()
    break

xi: tensor([[2.4000]])
yi: tensor([0])
outputs: tensor([[-0.1184,  0.4334]])
loss: 1.0066215991973877


In [62]:
print(model.linear1.weight.grad)
print(model.linear1.bias.grad)

tensor([[0.0022]])
tensor([0.0009])


In [63]:
print(model.linear2.weight.grad)
print(model.linear2.bias.grad)

tensor([[-0.0115]])
tensor([-0.0128])


In [64]:
print(model.linear3.weight.grad)
print(model.linear3.bias.grad)

tensor([[-0.0129]])
tensor([-0.0397])


In [65]:
print(model.linear4.weight.grad)
print(model.linear4.bias.grad)

tensor([[0.1335]])
tensor([0.2162])


In [66]:
print(model.linear5.weight.grad)
print(model.linear5.bias.grad)

tensor([[-0.2427],
        [ 0.2427]])
tensor([-0.6345,  0.6345])


In [67]:
print(model.linear1.weight)
print(model.linear1.bias)

Parameter containing:
tensor([[0.9197]], requires_grad=True)
Parameter containing:
tensor([-9.2881e-06], requires_grad=True)


In [68]:
print(model.linear2.weight)
print(model.linear2.bias)

Parameter containing:
tensor([[-0.8127]], requires_grad=True)
Parameter containing:
tensor([0.0001], requires_grad=True)


In [69]:
print(model.linear3.weight)
print(model.linear3.bias)

Parameter containing:
tensor([[1.4713]], requires_grad=True)
Parameter containing:
tensor([0.0004], requires_grad=True)


In [70]:
print(model.linear4.weight)
print(model.linear4.bias)

Parameter containing:
tensor([[-0.7780]], requires_grad=True)
Parameter containing:
tensor([-0.0022], requires_grad=True)


In [71]:
print(model.linear5.weight)
print(model.linear5.bias)

Parameter containing:
tensor([[-0.3072],
        [ 1.1309]], requires_grad=True)
Parameter containing:
tensor([ 0.0063, -0.0063], requires_grad=True)
